### ISSUE TITLE
Files sidebar icon click UX inconsistency

### ISSUE THREAD

**Issue by wiswedel** [juliushaertl/nextcloud-vue-collections#300]
Click on the Projects icon (1) opens the projects selector.
All other functions (Share link, others with access, internal link) require clicking on the right-side-icons (2).

18.0.0 daily build 2019-12-09

![image](https://user-images.githubusercontent.com/1804221/70520025-2cfdb180-1b3d-11ea-8d75-0f093c6096c6.png)

**Comment by jancborchardt** [comment]
Just to be clear, for almost all of these actions, the full area should be click-sensitive.

- Others with access: for sure should be, there’s no reason only the icon is
- Internal link: Also no reason to not copy the link when clicking anywhere on the entry
- Share link: Same thing. It literally says "Share link", and that’s what the action should do

**Comment by juliushaertl** [comment]
So the projects entry behaves as it should, just the others need to be fixed. Moving to server
